FRANXX_BUILD_TYPE ?= RELEASE

FRANXX_DATE_YEAR := $(shell date -u +%Y)
FRANXX_DATE_MONTH := $(shell date -u +%m)
FRANXX_DATE_DAY := $(shell date -u +%d)
FRANXX_DATE_HOUR := $(shell date -u +%H)
FRANXX_DATE_MINUTE := $(shell date -u +%M)
FRANXX_BUILD_DATE_UTC := $(shell date -d '$(FRANXX_DATE_YEAR)-$(FRANXX_DATE_MONTH)-$(FRANXX_DATE_DAY) $(FRANXX_DATE_HOUR):$(FRANXX_DATE_MINUTE) UTC' +%s)
FRANXX_BUILD_DATE := $(FRANXX_DATE_YEAR)$(FRANXX_DATE_MONTH)$(FRANXX_DATE_DAY)-$(FRANXX_DATE_HOUR)$(FRANXX_DATE_MINUTE)

FRANXX_PLATFORM_VERSION := 15

FRANXX_VERSION := FranxxOS_$(FRANXX_BUILD)-$(FRANXX_PLATFORM_VERSION)-$(FRANXX_BUILD_DATE)-$(FRANXX_BUILD_TYPE)
FRANXX_VERSION_PROP := 十五
